### ISSUE TITLE
Add "confirm password" on sign up screen

### ISSUE THREAD

**Issue by SumitNalavade** [aggie-coding-club/12th-rec#1]
- Add an additional input to the sign up screen confirm that the password the user is trying to sign up with is correct.
- This should be done through some kind of form control (https://docs.nativebase.io/form-control
- Don't worry about actually linking it with Firebase for now, just implement the UI

Example: 
![Responsewhenattempttosignupwithdifferentpasswordandconfirmpasswordinputs](https://user-images.githubusercontent.com/48499839/192076413-2b693893-7545-4a31-bf03-b77443b7e0f1.png)

**Comment by AaronS16** [comment]
Good Morning. I would like to give this a try if you would assign me please.

**Comment by SumitNalavade** [comment]
@AaronS16 Go for it!

**Comment by AaronS16** [comment]
@SumitNalavade I apologize I misread this originally. I'm not familiar with form control and wouldn't know where to start.

**Comment by SumitNalavade** [comment]
@AaronS16 Yeah so basically what a form control does is it verifies certain requirements are met before submitting a form. If those aren’t met there will be a small pop up show to notify the user.


https://stackoverflow.com/questions/31739685/what-is-a-form-control-in-html

To add in a form control for this app you can reference the native base docs I linked above.

lmk if you’re still interested in this issue

**Comment by SumitNalavade** [comment]
Merged
